# Utilizar este arquivo para realização das correções.

diretorio_recuperacao_ap1_n2 = '../../N2-AP1 Recuperação'

# Recuperação AP1-N2: Questões, rubricas e pontuação máxima
Recuperacao_ap1_n2_questoes = ['1a) Uma empresa de recrutamento on-line deseja avaliar o potencial de seus assinantes que estão em busca de emprego. Para isso, reuniu um conjunto de dados contendo informações sobre candidatos que aplicaram para uma vaga, juntamente com o resultado final da análise da empresa empregadora: "Aceito" ou "Rejeitado". Cada candidato possui três atributos: Experiência (Alta/Baixa); Graduação (Sim/Não); Habilidades Técnicas (Boa/Ruim). A empresa deseja construir uma árvore de decisão para prever se um candidato será aceito ou rejeitado com base nesses atributos. Explique como a entropia e o ganho de informação são utilizados para decidir qual atributo deve ser escolhido como raiz da árvore de decisão.',
                   '1b) Uma empresa de recrutamento on-line deseja avaliar o potencial de seus assinantes que estão em busca de emprego. Para isso, reuniu um conjunto de dados contendo informações sobre candidatos que aplicaram para uma vaga, juntamente com o resultado final da análise da empresa empregadora: "Aceito" ou "Rejeitado". Cada candidato possui três atributos: Experiência (Alta/Baixa); Graduação (Sim/Não); Habilidades Técnicas (Boa/Ruim). A empresa deseja construir uma árvore de decisão para prever se um candidato será aceito ou rejeitado com base nesses atributos. Suponha que a entropia inicial do conjunto seja 0.94. Após dividir os dados com base no atributo Experiência, obtemos: Candidatos com Experiência: 42 Aceitos e 7 Rejeitados; Candidatos sem Experiência: 12 Aceitos e 78 Rejeitados. Calcule o ganho de informação desse atributo e interprete o resultado.',
                   '2) Uma empresa de e-commerce deseja prever se um cliente comprará ou não um produto após visualizar a página do item. Para isso, foi analisado um conjunto de 200 interações de clientes e coletados os seguintes atributos: Tempo na Página (Curto ou Longo); Dispositivo (Mobile ou Desktop); Origem do Tráfego (Orgânico ou Pago). A tabela a seguir resume os dados coletados para treinamento de um algoritmo de classificação: ||Característica | Comprou (Sim) | Não Comprou (Não) || Tempo na Página = Longo | 60 | 30 || Tempo na Página = Curto | 20 | 90 || Dispositivo = Desktop | 50 | 50 || Dispositivo = Mobile | 30 | 70 || Origem do Tráfego = Orgânico | 40 | 40 || Origem do Tráfego = Pago | 40 | 60||. Sabemos que 80 clientes compraram o produto e 120 não compraram. Suponha que um novo usuário acessa a página do produto com as seguintes características: Tempo na Página = Longo; Dispositivo = Desktop; Origem do Tráfego = Orgânico. Com base nos dados de treinamento, como o algoritmo Naive Bayes classificaria este cliente? Considere: P(A|B,C,...,Z)=(P(A)P(B|A)P(C|A)...P(Z|A))/(P(B)P(C)...P(Z)).']

Recuperacao_ap1_n2_rubricas=[
    {('Citar e/ou explicitar o cálculo da entropia inicial de "Aceito" ou "Rejeitado" antes de realizar a partição.', 0,9),
     ('Citar e/ou explicitar o cálculo da entropia final de "Aceito" ou "Rejeitado" considerando as partições possíveis no atributo que está sendo analisado.', 0,9),
     ('Citar e/ou explicar o calculo de Information Gain (IG) como sendo IG = Entropia(Antes da partição) - Entropia(Após partição), considerando que o maior IG define qual atributo será escolhido', 0.9)},
       {('Citar e/ou explicitar o cálculo da entropia do grupo de amostras formadas para H(Experiência == "Alta")=-(42/49)*log2(42/49)-(7/49)*log2(7/49)~0.59', 1.0),
        ('Citar e/ou explicitar o cálculo da entropia do grupo de amostras formadas para H(Experiência != "Alta")=-(12/90)*log2(12/90)-(78/90)*log2(78/90)~0.57', 0.8),
         ('Citar e/ou explicar o cálculo da entropia ponderada após a partição Experiência == "Alta", H("Experiencia Alta")=(49/139)*0.59+(90/139)*0.57~0.58', 0.8),
        ('Citar e/ou explicar o cálculo do ganho de informação (Information Gain, IG) como sendo IG("Experiencia Alta")~0.94-0.58=0.36', 1.0),
        ('Citar e/ou explicar que um ganho de informação maior que zero demonstra maior homogeneidade dos subconjuntos após a partição "Experiencia Alta".', 0.5)},
          {('Citar e/ou explicitar o cálculo P(Compra|Tempo Longo, Dispositivo Desktop, Tráfego Orgânico)=[(80/200)*(60/80)*(50/80)*(40/80)]/[(90/200)*(100/200)*(80/180)]~0.94 ou memso a simplificação P(Compra|Tempo Longo, Dispositivo Desktop, Tráfego Orgânico)=[(80/200)*(60/80)*(50/80)*(40/80)]~0.094, desconsiderando o denominador P(Tempo Longo)*P(Dispositivo Desktop)*P(Tráfego Orgânico) tendo em vista que irá comparar com a P(Não Compra|Tempo Longo, Dispositivo Desktop, Tráfego Orgânico) com a mesma simplificação.', 2.0),
           ('Citar e/ou explicitar o cálculo P(Não Compra|Tempo Longo, Dispositivo Desktop, Tráfego Orgânico)=[(120/200)*(30/120)*(50/120)*(40/100)]/[(90/200)*(100/200)*(80/180)]=0.25 ou mesmo a simplificação P(Não Compra|Tempo Longo, Dispositivo Desktop, Tráfego Orgânico)=[(120/200)*(30/120)*(50/120)*(40/100)]=0.025, desconsiderando o denominador P(Tempo Longo)*P(Dispositivo Desktop)*P(Tráfego Orgânico) tendo em vista que irá comparar com a P(Não Compra|Tempo Longo, Dispositivo Desktop, Tráfego Orgânico) com a mesma simplificação.', 2.0),
            ('Citar e/ou explicitar que, usando Naive Bayes, dado a probabilidade P(Compra|Tempo Longo, Dispositivo Desktop, Tráfego Orgânico)~0.94 ou ~0.094 (simplificando denominador de ambas fórmulas) e P(Não Compra|Tempo Longo, Dispositivo Desktop, Tráfego Orgânico)=0.25 ou 0.025 (simplificando denominador de ambas fórmulas), o sistema apontaria que o cliente irá comprar na plataforma.', 2.0)}]

Recuperacao_ap1_n2_pontuacao_maxima = [2.5, 2.5, 5.0]

Recuperacao_ap1_n2 = [Recuperacao_ap1_n2_questoes, Recuperacao_ap1_n2_rubricas, Recuperacao_ap1_n2_pontuacao_maxima]